#!/usr/bin/env python3
"""Render compose.tool.yml from AGENT_TOOL (tool-specific volume mounts)."""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from agents.tool_specs import get_tool_spec, get_volume_mounts, validate_tool

OUTPUT = ROOT / "compose.tool.yml"
ENV_FILE = ROOT / ".env"


def load_env_file(path: Path = ENV_FILE) -> None:
    """Load KEY=VALUE pairs from .env without overriding existing env vars."""
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


def main() -> None:
    load_env_file()
    tool = validate_tool(os.environ.get("AGENT_TOOL", "agy"))
    spec = get_tool_spec(tool)
    mounts = get_volume_mounts(tool)

    lines = [
        "# Generated by scripts/render_compose_overlay.py — do not edit manually.",
        f"# AGENT_TOOL={tool}",
        "services:",
        "  agent:",
        "    volumes:",
    ]

    for host_path, container_path in mounts:
        lines.append(f"      - {host_path}:{container_path}:Z")

    if spec.optional_env_vars:
        lines.append("    environment:")
        for env_name in spec.optional_env_vars:
            lines.append(f"      - {env_name}=${{{env_name}}}")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT} for AGENT_TOOL={tool}", flush=True)


if __name__ == "__main__":
    main()
